# Generated by Django 4.1 on 2024-08-14 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uanl_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependicia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=264, unique=True)),
                ('informacion', models.CharField(max_length=4000, unique=True)),
                ('Dependicia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='uanl_app.dependicia')),
            ],
        ),
    ]
