# Generated by Django 4.1 on 2024-08-14 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uanl_app', '0002_dependicia_servicio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dependicia',
            new_name='Dependencia',
        ),
    ]
